project:
  type: website
  output-dir: _site
  preview:
    port: 4321
    browser: false

website:
  title: "Essi Alizadeh"
  description: "Personal website"
  site-url: https://new.ealizadeh.com
  repo-url: https://github.com/e-alizadeh/website   
  favicon: assets/favicon.png
  open-graph: true
  google-analytics: "UA-180647948-1"
  twitter-card: 
    creator: "@es_alizadeh"
    site: "@es_alizadeh"
    card-style: "summary_large_image"
  navbar:
    background: dark
    foreground: light
    left:
      - href: index.qmd
        text: Home
      - blog.qmd
      - contact_me.qmd
      # - subscribe.qmd
  page-footer: 
    border: false
    # background: light
    center: "©️ 2022 Esmaeil Alizadeh - All Rights Reserved" 
    right: 
      - icon: github
        href: https://github.com/e-alizadeh
      - icon: twitter 
        href: https://twitter.com/es_alizadeh

bibliography: 
  - "bibliographies/references.bib"
  - "bibliographies/online.bib"
  - "bibliographies/wikipedia.bib"

format:
  html:
    theme: 
      light: cosmo
      # dark: darkly
    css: styles.css
    code-copy: true
    code-overflow: wrap
    html-math-method: katex
    smooth-scroll: true
    highlight-style: tango
    fig-align: center
    include-in-header:
      - assets/external_style.html

execute:
  freeze: auto