project:
  type: website
  output-dir: _site

website:
  title: "Essi Alizadeh"
  description: "Personal website"
  site-url: https://ealizadeh.com
  repo-url: https://github.com/e-alizadeh/website   
  favicon: assets/favicon.png
  open-graph: true
  google-analytics: "UA-180647948-1"
  twitter-card: 
    creator: "@es_alizadeh"
    site: "@es_alizadeh"
    card-style: "summary_large_image"
  navbar:
    background: dark
    foreground: light
    left:
      - href: index.qmd
        text: Home
      - blog.qmd
      - about.qmd
  page-footer: 
    border: false
    # background: light
    center: "©️ 2022 Esmaeil Alizadeh - All Rights Reserved" 
    right: 
      - icon: github
        href: https://github.com/e-alizadeh
      - icon: twitter 
        href: https://twitter.com/es_alizadeh

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    html-math-method: katex
    highlight-style: tango
    include-in-header:
      - assets/external_style.html




